p=input('digite algo')
print(f'o tipo primitivo é:', {type(p)})
print(f'é númerico?', {p.isnumeric()})
print(f'é letras', {p.isalpha()})
print(f'é númerico é letra?', {p.isalnum()})
print(f'é somente espaço?', {p.isspace()})
print(f'é minuscula?', {p.islower()})
print(f'é ??', {p.isascii()})
print(f'é decimal?', {p.isdecimal()})
print(f'é maiuscula?', {p.isupper()})
print(f'é identificador?', {p.isidentifier()})
print(f'é digito?', {p.isdigit()})
print(f'está capitalizada?', {p.istitle()})