nc=input('Qual seu nome completo?')
nm= nc.upper()
nmm= nc.lower()
pn= nc.split()
tl= len(nc)-nc.count(' ')
print('Maiuscula:{}'.format(nm))
print('Minuscula:{}'.format(nmm))
print('O seu primeiro nome possui {} letras'.format(len(pn[0])))
print('O seu nome todo tem {} letras'. format(tl))